### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by mikk67485** [tikene/AntiAntiPlagiarism#1]
Can you make this program work in word .doc / docx?
I am ready to pay the required price. thank you

**Comment by tikene** [comment]
Please contact me over tikenemail@gmail.com with the details

**Comment by AdVeNtUrE-Black** [comment]
Hi, I just **sent you an email**. 
I am interested in working with you to develop this project.
I think it can be a good job for you.
Thank you and I await your reply.

**Comment by tikene** [comment]
Hello!
Can you tell me a little bit about what you would like to have done and
what would the payment be?
I await your reply :)

**Comment by AdVeNtUrE-Black** [comment]
Hi,
I want to hide plagiarism in word documents (.doc / .docx).
I think your method can pass most plagiarism checking programs, but the 
documents that need to be checked for plagiarism are sent in .doc/.docx 
format.
So I need your program made to work for word documents
I pay as much as you ask, if you can make it work for documents in ms 
word.
Thanks

**Comment by AdVeNtUrE-Black** [comment]
Thank you and I await your reply.

**Comment by AdVeNtUrE-Black** [comment]
Still awaiting your reply. Thanks

**Comment by tikene** [comment]
Hi, sorry for not replying earlier. Send me your Telegram @ and I'll message you

**Comment by AdVeNtUrE-Black** [comment]
Email sent with my telegram

⁣Get BlueMail for Android ​
